pipeline {
  agent any

  stages {
    stage('build') {
      steps {
        // One or more steps need to be included within the steps block.
        echo 'Building...'
      }
    }

    stage('test') {
      steps {
        // One or more steps need to be included within the steps block.
        echo 'Testing...'

      }
    }

    stage('deploy') {
      steps {
        // One or more steps need to be included within the steps block.
        echo 'Deploying...'
        echo 'Done!'

      }
    }

  }

}